void tori(int x, int y, int z, int i);
void ground();
void wayStoneStep();
void gate(float x,float y,float z, float width, int height);
void surroundStoneStep();
void building(float minLength, float maxLength, float depth, float height);
void protoBuilding();
void signboard();
void tree();
void generateTree();
void loadway();
